folders:
  - root_path: "/path/to/workload1"
  - root_path: "/path/to/workload2"
  - root_path: "/path/to/workload3"
ignore_folders:
  - root_path: .git
  - root_path: .conda
  - root_path: .cache
  - root_path: .build
  - root_path: .env
  - root_path: .local

keywords:
  - library
  - SparkR
  - from_unixtime
  - unix_timestamp
  - from_utc_timestamp
  - locate
  - instr
  - datediff
  - date_add
  - date_sub
  - date_format
  - struct
  - named_struct
  - array_max/array_min
  - array_agg
  - arrays_zip
  - array
  - collect_list
  - collect_set
  - explode / explode_outer
  - map_from_arrays
  - from_json
